config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'user/:id', to: 'users#show', as: :user
  resources :users, only: [:show]
  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :rsvps, only: [:index, :show, :new, :create, :destroy]
  
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :rsvps, foreign_key: :attended_event_id, class_name: "Rsvp"
  has_many :attendees, through: :rsvps

  validates :name, presence: true

  scope :past_events, -> { where("date < ?", Time.current) }
  scope :upcoming_events, -> { where("date >= ?", Time.current) }

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord

  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  has_many :rsvps, foreign_key: :attendee_id, class_name: "Rsvp"
  has_many :attended_events, through: :rsvps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # permitting additional parameters, in this case :name
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location, :description)
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
    @rsvp = Rsvp.new(rsvp_params)

    if @rsvp.save
      redirect_to events_path
    end
  end

  def destroy
    user_id = current_user.id
    event = Event.find(params[:id])
    event_id = event.id
    # using a finder method to an instance of Rsvp
    # using where would return an activerecord::relation
    @rsvp = Rsvp.find_by(attendee_id: user_id, attended_event_id: event_id)
    @rsvp.destroy

    redirect_to events_path
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:attended_event_id, :attendee_id)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <%= form.label("Name") %>
  <%= form.text_field(:name, placeholder: "Name of your event") %><br><br>
  <% event.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <%= form.label("Date") %>
  <%= form.text_field(:date, placeholder: "YYYY/MM/DD") %><br><br>
  <%= form.label("Location") %>
  <%= form.text_field(:location) %><br><br>
  <%= form.label("Description") %>
  <%= form.text_field(:description) %><br><br>
  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Update <%= @event.name %></h1>

<%= render "form", event: @event%><br>

<%= link_to "Cancel", @event %>

app/views/events/index.html.erb
<div>
  <h1>Showing all Events</h1>
</div>
<% if user_signed_in? %>
  <% if @events.nil? %>
    <%= "No Events" %>
  <% else %>
    <%= "Upcoming Events: " %><br>
    <% @upcoming_events.each do |event| %>
      <%= link_to event.name, event %><br>
    <% end %><br><br>
    <%= "Past Events:" %><br>
    <% @past_events.each do |event| %>
      <%= link_to event.name, event %><br>
    <% end %>
    <br><br>
  <% end %>
  <div><%= link_to "New Event", new_event_path %></div>
  <div><%= link_to "My Events", user_path(current_user) %></div>
<% else %>
  <h3>Sign In or Register to see event details</h3>
  <%= "Upcoming Events: " %><br>
  <% @upcoming_events.each do |event| %>
    <%= event.name%><br>
  <% end %>  <br><br>
  <%= "Past Events:" %><br>
  <% @past_events.each do |event| %>
    <%= event.name %><br>
  <% end %>
  <br><br>
<% end %><br><br>

app/views/events/new.html.erb
<h1>Create a new event!</h1>

<%= render "form", event: @event%>

app/views/events/show.html.erb
<h1>See details about <%= @event.name %> below</h1>
Creator: <%= @event.creator.name %><br>
<%= @event.name %><br>
<%= @event.date %><br>
<%= @event.location %><br>
<%= @event.description %><br>
Attendees: 
<%# grab the event attendees and iterate thru them to grab their names %>
<% @event.attendees.each do |attendee| %>
  <%= attendee.name %>
<% end %>

<br><br>

<%# check if the current user has rvsped to the event - attentee_ids acts as an array %>
<% if @event.attendee_ids.include?(current_user.id) %>
  <%= link_to "Cancel RSVP", rsvp_path, method: :delete %>
<% else %>
  <%= form_with model: Rsvp.new do |form| %>
    <%= form.hidden_field :attended_event_id, value: @event.id %>
    <%= form.hidden_field :attendee_id, value: current_user.id %>
    <%= form.submit "RSVP" %>
  <% end %>
<% end %>


<% if @event.creator == current_user %>
  <div><%= link_to "Edit #{@event.name}", edit_event_path %></div>
  <div><%= link_to "Delete", event_path, method: :delete %></div>
<% end %>

app/views/layouts/_header.html.erb
<div class="site-header">
<% if user_signed_in? %>
  <div class="logo" >
    <%= link_to "Private Events", events_path %> 
  </div>
  <div class="nav-links">
    <%= link_to "My Profile", current_user %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
    </div>
<% else %>
  <div class="logo" >
    <%= link_to "Private Events", events_path %> 
  </div>
  <div class="nav-links">
    <%= link_to "Sign In", user_session_path %><br>
    <%= link_to "Register", new_user_registration_path %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/rsvps/index.html.erb
<h1>Rsvp#index</h1>

app/views/rsvps/new.html.erb
<h1>Rsvp#new</h1>
<p>Find me in app/views/rsvp/new.html.erb</p>

app/views/rsvps/show.html.erb
<h1>Rsvp#show</h1>
<p>Find me in app/views/rsvp/show.html.erb</p>

app/views/users/show.html.erb
<h1>Hello <%= @user.name %>, see your created events below</h1>
<% @user.created_events.each do |event| %>
  <%= link_to event.name, event %><br><br>
<% end %>

<h1>Events RSVPed to</h1>
<h3>Upcoming Events:</h3>
<% upcoming_events = @user.attended_events.upcoming_events %>
<% upcoming_events.each do |event| %>
  <%= link_to event.name, event %><br>
<% end %>

<h3>Past Events:</h3>
<% past_events = @user.attended_events.past_events %>
<% past_events.each do |event| %>
  <%= link_to event.name, event %><br>
<% end %>